// Generated enums and structures for Mavlink dialect standard #0 version 3
package standard

// Generated by gomavlink, DO NOT EDIT.

import (
	"math"

	mavlink "github.com/lvdlvd/gomavlink"
)

//go:generate stringer -output strings.go -type=MavAutopilot,MavType,MavModeFlag,MavModeFlagDecodePosition,MavState,MavComponent,MavBool,MavProtocolCapability,FirmwareVersionType

/* Micro air vehicle / autopilot classes. This identifies the individual model. */
type MavAutopilot uint32

const (
	/* Generic autopilot, full support for everything */
	MAV_AUTOPILOT_GENERIC MavAutopilot = 0

	/* Reserved for future use. */
	MAV_AUTOPILOT_RESERVED MavAutopilot = 1

	/* SLUGS autopilot, http://slugsuav.soe.ucsc.edu */
	MAV_AUTOPILOT_SLUGS MavAutopilot = 2

	/* ArduPilot - Plane/Copter/Rover/Sub/Tracker, https://ardupilot.org */
	MAV_AUTOPILOT_ARDUPILOTMEGA MavAutopilot = 3

	/* OpenPilot, http://openpilot.org */
	MAV_AUTOPILOT_OPENPILOT MavAutopilot = 4

	/* Generic autopilot only supporting simple waypoints */
	MAV_AUTOPILOT_GENERIC_WAYPOINTS_ONLY MavAutopilot = 5

	/* Generic autopilot supporting waypoints and other simple navigation commands */
	MAV_AUTOPILOT_GENERIC_WAYPOINTS_AND_SIMPLE_NAVIGATION_ONLY MavAutopilot = 6

	/* Generic autopilot supporting the full mission command set */
	MAV_AUTOPILOT_GENERIC_MISSION_FULL MavAutopilot = 7

	/* No valid autopilot, e.g. a GCS or other MAVLink component */
	MAV_AUTOPILOT_INVALID MavAutopilot = 8

	/* PPZ UAV - http://nongnu.org/paparazzi */
	MAV_AUTOPILOT_PPZ MavAutopilot = 9

	/* UAV Dev Board */
	MAV_AUTOPILOT_UDB MavAutopilot = 10

	/* FlexiPilot */
	MAV_AUTOPILOT_FP MavAutopilot = 11

	/* PX4 Autopilot - http://px4.io/ */
	MAV_AUTOPILOT_PX4 MavAutopilot = 12

	/* SMACCMPilot - http://smaccmpilot.org */
	MAV_AUTOPILOT_SMACCMPILOT MavAutopilot = 13

	/* AutoQuad -- http://autoquad.org */
	MAV_AUTOPILOT_AUTOQUAD MavAutopilot = 14

	/* Armazila -- http://armazila.com */
	MAV_AUTOPILOT_ARMAZILA MavAutopilot = 15

	/* Aerob -- http://aerob.ru */
	MAV_AUTOPILOT_AEROB MavAutopilot = 16

	/* ASLUAV autopilot -- http://www.asl.ethz.ch */
	MAV_AUTOPILOT_ASLUAV MavAutopilot = 17

	/* SmartAP Autopilot - http://sky-drones.com */
	MAV_AUTOPILOT_SMARTAP MavAutopilot = 18

	/* AirRails - http://uaventure.com */
	MAV_AUTOPILOT_AIRRAILS MavAutopilot = 19

	/* Fusion Reflex - https://fusion.engineering */
	MAV_AUTOPILOT_REFLEX MavAutopilot = 20
)

/* MAVLINK component type reported in HEARTBEAT message. Flight controllers must report the type of the vehicle on which they are mounted (e.g. MAV_TYPE_OCTOROTOR). All other components must report a value appropriate for their type (e.g. a camera must use MAV_TYPE_CAMERA). */
type MavType uint32

const (
	/* Generic micro air vehicle */
	MAV_TYPE_GENERIC MavType = 0

	/* Fixed wing aircraft. */
	MAV_TYPE_FIXED_WING MavType = 1

	/* Quadrotor */
	MAV_TYPE_QUADROTOR MavType = 2

	/* Coaxial helicopter */
	MAV_TYPE_COAXIAL MavType = 3

	/* Normal helicopter with tail rotor. */
	MAV_TYPE_HELICOPTER MavType = 4

	/* Ground installation */
	MAV_TYPE_ANTENNA_TRACKER MavType = 5

	/* Operator control unit / ground control station */
	MAV_TYPE_GCS MavType = 6

	/* Airship, controlled */
	MAV_TYPE_AIRSHIP MavType = 7

	/* Free balloon, uncontrolled */
	MAV_TYPE_FREE_BALLOON MavType = 8

	/* Rocket */
	MAV_TYPE_ROCKET MavType = 9

	/* Ground rover */
	MAV_TYPE_GROUND_ROVER MavType = 10

	/* Surface vessel, boat, ship */
	MAV_TYPE_SURFACE_BOAT MavType = 11

	/* Submarine */
	MAV_TYPE_SUBMARINE MavType = 12

	/* Hexarotor */
	MAV_TYPE_HEXAROTOR MavType = 13

	/* Octorotor */
	MAV_TYPE_OCTOROTOR MavType = 14

	/* Tricopter */
	MAV_TYPE_TRICOPTER MavType = 15

	/* Flapping wing */
	MAV_TYPE_FLAPPING_WING MavType = 16

	/* Kite */
	MAV_TYPE_KITE MavType = 17

	/* Onboard companion controller */
	MAV_TYPE_ONBOARD_CONTROLLER MavType = 18

	/* Two-rotor Tailsitter VTOL that additionally uses control surfaces in vertical operation. Note, value previously named MAV_TYPE_VTOL_DUOROTOR. */
	MAV_TYPE_VTOL_TAILSITTER_DUOROTOR MavType = 19

	/* Quad-rotor Tailsitter VTOL using a V-shaped quad config in vertical operation. Note: value previously named MAV_TYPE_VTOL_QUADROTOR. */
	MAV_TYPE_VTOL_TAILSITTER_QUADROTOR MavType = 20

	/* Tiltrotor VTOL. Fuselage and wings stay (nominally) horizontal in all flight phases. It able to tilt (some) rotors to provide thrust in cruise flight. */
	MAV_TYPE_VTOL_TILTROTOR MavType = 21

	/* VTOL with separate fixed rotors for hover and cruise flight. Fuselage and wings stay (nominally) horizontal in all flight phases. */
	MAV_TYPE_VTOL_FIXEDROTOR MavType = 22

	/* Tailsitter VTOL. Fuselage and wings orientation changes depending on flight phase: vertical for hover, horizontal for cruise. Use more specific VTOL MAV_TYPE_VTOL_TAILSITTER_DUOROTOR or MAV_TYPE_VTOL_TAILSITTER_QUADROTOR if appropriate. */
	MAV_TYPE_VTOL_TAILSITTER MavType = 23

	/* Tiltwing VTOL. Fuselage stays horizontal in all flight phases. The whole wing, along with any attached engine, can tilt between vertical and horizontal mode. */
	MAV_TYPE_VTOL_TILTWING MavType = 24

	/* VTOL reserved 5 */
	MAV_TYPE_VTOL_RESERVED5 MavType = 25

	/* Gimbal */
	MAV_TYPE_GIMBAL MavType = 26

	/* ADSB system */
	MAV_TYPE_ADSB MavType = 27

	/* Steerable, nonrigid airfoil */
	MAV_TYPE_PARAFOIL MavType = 28

	/* Dodecarotor */
	MAV_TYPE_DODECAROTOR MavType = 29

	/* Camera */
	MAV_TYPE_CAMERA MavType = 30

	/* Charging station */
	MAV_TYPE_CHARGING_STATION MavType = 31

	/* FLARM collision avoidance system */
	MAV_TYPE_FLARM MavType = 32

	/* Servo */
	MAV_TYPE_SERVO MavType = 33

	/* Open Drone ID. See https://mavlink.io/en/services/opendroneid.html. */
	MAV_TYPE_ODID MavType = 34

	/* Decarotor */
	MAV_TYPE_DECAROTOR MavType = 35

	/* Battery */
	MAV_TYPE_BATTERY MavType = 36

	/* Parachute */
	MAV_TYPE_PARACHUTE MavType = 37

	/* Log */
	MAV_TYPE_LOG MavType = 38

	/* OSD */
	MAV_TYPE_OSD MavType = 39

	/* IMU */
	MAV_TYPE_IMU MavType = 40

	/* GPS */
	MAV_TYPE_GPS MavType = 41

	/* Winch */
	MAV_TYPE_WINCH MavType = 42

	/* Generic multirotor that does not fit into a specific type or whose type is unknown */
	MAV_TYPE_GENERIC_MULTIROTOR MavType = 43

	/* Illuminator. An illuminator is a light source that is used for lighting up dark areas external to the system: e.g. a torch or searchlight (as opposed to a light source for illuminating the system itself, e.g. an indicator light). */
	MAV_TYPE_ILLUMINATOR MavType = 44

	/* Orbiter spacecraft. Includes satellites orbiting terrestrial and extra-terrestrial bodies. Follows NASA Spacecraft Classification. */
	MAV_TYPE_SPACECRAFT_ORBITER MavType = 45

	/* A generic four-legged ground vehicle (e.g., a robot dog). */
	MAV_TYPE_GROUND_QUADRUPED MavType = 46

	/* VTOL hybrid of helicopter and autogyro. It has a main rotor for lift and separate propellers for forward flight. The rotor must be powered for hover but can autorotate in cruise flight. See: https://en.wikipedia.org/wiki/Gyrodyne */
	MAV_TYPE_VTOL_GYRODYNE MavType = 47

	/* Gripper */
	MAV_TYPE_GRIPPER MavType = 48

	/* Radio */
	MAV_TYPE_RADIO MavType = 49
)

/* These flags encode the MAV mode, see MAV_MODE enum for useful combinations. */
type MavModeFlag uint32

const (
	/* 0b10000000 MAV safety set to armed. Motors are enabled / running / can start. Ready to fly. Additional note: this flag is to be ignore when sent in the command MAV_CMD_DO_SET_MODE and MAV_CMD_COMPONENT_ARM_DISARM shall be used instead. The flag can still be used to report the armed state. */
	MAV_MODE_FLAG_SAFETY_ARMED MavModeFlag = 128

	/* 0b01000000 remote control input is enabled. */
	MAV_MODE_FLAG_MANUAL_INPUT_ENABLED MavModeFlag = 64

	/* 0b00100000 hardware in the loop simulation. All motors / actuators are blocked, but internal software is full operational. */
	MAV_MODE_FLAG_HIL_ENABLED MavModeFlag = 32

	/* 0b00010000 system stabilizes electronically its attitude (and optionally position). It needs however further control inputs to move around. */
	MAV_MODE_FLAG_STABILIZE_ENABLED MavModeFlag = 16

	/* 0b00001000 guided mode enabled, system flies waypoints / mission items. */
	MAV_MODE_FLAG_GUIDED_ENABLED MavModeFlag = 8

	/* 0b00000100 autonomous mode enabled, system finds its own goal positions. Guided flag can be set or not, depends on the actual implementation. */
	MAV_MODE_FLAG_AUTO_ENABLED MavModeFlag = 4

	/* 0b00000010 system has a test mode enabled. This flag is intended for temporary system tests and should not be used for stable implementations. */
	MAV_MODE_FLAG_TEST_ENABLED MavModeFlag = 2

	/* 0b00000001 system-specific custom mode is enabled. When using this flag to enable a custom mode all other flags should be ignored. */
	MAV_MODE_FLAG_CUSTOM_MODE_ENABLED MavModeFlag = 1
)

/* These values encode the bit positions of the decode position. These values can be used to read the value of a flag bit by combining the base_mode variable with AND with the flag position value. The result will be either 0 or 1, depending on if the flag is set or not. */
type MavModeFlagDecodePosition uint32

const (
	/* First bit:  10000000 */
	MAV_MODE_FLAG_DECODE_POSITION_SAFETY MavModeFlagDecodePosition = 128

	/* Second bit: 01000000 */
	MAV_MODE_FLAG_DECODE_POSITION_MANUAL MavModeFlagDecodePosition = 64

	/* Third bit:  00100000 */
	MAV_MODE_FLAG_DECODE_POSITION_HIL MavModeFlagDecodePosition = 32

	/* Fourth bit: 00010000 */
	MAV_MODE_FLAG_DECODE_POSITION_STABILIZE MavModeFlagDecodePosition = 16

	/* Fifth bit:  00001000 */
	MAV_MODE_FLAG_DECODE_POSITION_GUIDED MavModeFlagDecodePosition = 8

	/* Sixth bit:   00000100 */
	MAV_MODE_FLAG_DECODE_POSITION_AUTO MavModeFlagDecodePosition = 4

	/* Seventh bit: 00000010 */
	MAV_MODE_FLAG_DECODE_POSITION_TEST MavModeFlagDecodePosition = 2

	/* Eighth bit: 00000001 */
	MAV_MODE_FLAG_DECODE_POSITION_CUSTOM_MODE MavModeFlagDecodePosition = 1
)

type MavState uint32

const (
	/* Uninitialized system, state is unknown. */
	MAV_STATE_UNINIT MavState = 0

	/* System is booting up. */
	MAV_STATE_BOOT MavState = 1

	/* System is calibrating and not flight-ready. */
	MAV_STATE_CALIBRATING MavState = 2

	/* System is grounded and on standby. It can be launched any time. */
	MAV_STATE_STANDBY MavState = 3

	/* System is active and might be already airborne. Motors are engaged. */
	MAV_STATE_ACTIVE MavState = 4

	/* System is in a non-normal flight mode (failsafe). It can however still navigate. */
	MAV_STATE_CRITICAL MavState = 5

	/* System is in a non-normal flight mode (failsafe). It lost control over parts or over the whole airframe. It is in mayday and going down. */
	MAV_STATE_EMERGENCY MavState = 6

	/* System just initialized its power-down sequence, will shut down now. */
	MAV_STATE_POWEROFF MavState = 7

	/* System is terminating itself (failsafe or commanded). */
	MAV_STATE_FLIGHT_TERMINATION MavState = 8
)

/* Legacy component ID values for particular types of hardware/software that might make up a MAVLink system (autopilot, cameras, servos, avoidance systems etc.).                Components are not required or expected to use IDs with names that correspond to their type or function, but may choose to do so.         Using an ID that matches the type may slightly reduce the chances of component id clashes, as, for historical reasons, it is less likely to be used by some other type of component.         System integration will still need to ensure that all components have unique IDs.          Component IDs are used for addressing messages to a particular component within a system.         A component can use any unique ID between 1 and 255 (MAV_COMP_ID_ALL value is the broadcast address, used to send to all components).                  Historically component ID were also used for identifying the type of component.         New code must not use component IDs to infer the component type, but instead check the MAV_TYPE in the HEARTBEAT message!        */
type MavComponent uint32

const (
	/* Target id (target_component) used to broadcast messages to all components of the receiving system. Components should attempt to process messages with this component ID and forward to components on any other interfaces. Note: This is not a valid *source* component id for a message. */
	MAV_COMP_ID_ALL MavComponent = 0

	/* System flight controller component ("autopilot"). Only one autopilot is expected in a particular system. */
	MAV_COMP_ID_AUTOPILOT1 MavComponent = 1

	/* Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network. */
	MAV_COMP_ID_USER1 MavComponent = 25

	/* Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network. */
	MAV_COMP_ID_USER2 MavComponent = 26

	/* Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network. */
	MAV_COMP_ID_USER3 MavComponent = 27

	/* Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network. */
	MAV_COMP_ID_USER4 MavComponent = 28

	/* Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network. */
	MAV_COMP_ID_USER5 MavComponent = 29

	/* Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network. */
	MAV_COMP_ID_USER6 MavComponent = 30

	/* Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network. */
	MAV_COMP_ID_USER7 MavComponent = 31

	/* Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network. */
	MAV_COMP_ID_USER8 MavComponent = 32

	/* Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network. */
	MAV_COMP_ID_USER9 MavComponent = 33

	/* Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network. */
	MAV_COMP_ID_USER10 MavComponent = 34

	/* Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network. */
	MAV_COMP_ID_USER11 MavComponent = 35

	/* Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network. */
	MAV_COMP_ID_USER12 MavComponent = 36

	/* Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network. */
	MAV_COMP_ID_USER13 MavComponent = 37

	/* Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network. */
	MAV_COMP_ID_USER14 MavComponent = 38

	/* Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network. */
	MAV_COMP_ID_USER15 MavComponent = 39

	/* Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network. */
	MAV_COMP_ID_USER16 MavComponent = 40

	/* Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network. */
	MAV_COMP_ID_USER17 MavComponent = 41

	/* Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network. */
	MAV_COMP_ID_USER18 MavComponent = 42

	/* Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network. */
	MAV_COMP_ID_USER19 MavComponent = 43

	/* Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network. */
	MAV_COMP_ID_USER20 MavComponent = 44

	/* Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network. */
	MAV_COMP_ID_USER21 MavComponent = 45

	/* Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network. */
	MAV_COMP_ID_USER22 MavComponent = 46

	/* Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network. */
	MAV_COMP_ID_USER23 MavComponent = 47

	/* Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network. */
	MAV_COMP_ID_USER24 MavComponent = 48

	/* Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network. */
	MAV_COMP_ID_USER25 MavComponent = 49

	/* Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network. */
	MAV_COMP_ID_USER26 MavComponent = 50

	/* Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network. */
	MAV_COMP_ID_USER27 MavComponent = 51

	/* Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network. */
	MAV_COMP_ID_USER28 MavComponent = 52

	/* Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network. */
	MAV_COMP_ID_USER29 MavComponent = 53

	/* Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network. */
	MAV_COMP_ID_USER30 MavComponent = 54

	/* Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network. */
	MAV_COMP_ID_USER31 MavComponent = 55

	/* Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network. */
	MAV_COMP_ID_USER32 MavComponent = 56

	/* Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network. */
	MAV_COMP_ID_USER33 MavComponent = 57

	/* Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network. */
	MAV_COMP_ID_USER34 MavComponent = 58

	/* Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network. */
	MAV_COMP_ID_USER35 MavComponent = 59

	/* Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network. */
	MAV_COMP_ID_USER36 MavComponent = 60

	/* Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network. */
	MAV_COMP_ID_USER37 MavComponent = 61

	/* Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network. */
	MAV_COMP_ID_USER38 MavComponent = 62

	/* Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network. */
	MAV_COMP_ID_USER39 MavComponent = 63

	/* Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network. */
	MAV_COMP_ID_USER40 MavComponent = 64

	/* Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network. */
	MAV_COMP_ID_USER41 MavComponent = 65

	/* Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network. */
	MAV_COMP_ID_USER42 MavComponent = 66

	/* Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network. */
	MAV_COMP_ID_USER43 MavComponent = 67

	/* Telemetry radio (e.g. SiK radio, or other component that emits RADIO_STATUS messages). */
	MAV_COMP_ID_TELEMETRY_RADIO MavComponent = 68

	/* Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network. */
	MAV_COMP_ID_USER45 MavComponent = 69

	/* Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network. */
	MAV_COMP_ID_USER46 MavComponent = 70

	/* Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network. */
	MAV_COMP_ID_USER47 MavComponent = 71

	/* Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network. */
	MAV_COMP_ID_USER48 MavComponent = 72

	/* Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network. */
	MAV_COMP_ID_USER49 MavComponent = 73

	/* Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network. */
	MAV_COMP_ID_USER50 MavComponent = 74

	/* Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network. */
	MAV_COMP_ID_USER51 MavComponent = 75

	/* Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network. */
	MAV_COMP_ID_USER52 MavComponent = 76

	/* Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network. */
	MAV_COMP_ID_USER53 MavComponent = 77

	/* Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network. */
	MAV_COMP_ID_USER54 MavComponent = 78

	/* Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network. */
	MAV_COMP_ID_USER55 MavComponent = 79

	/* Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network. */
	MAV_COMP_ID_USER56 MavComponent = 80

	/* Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network. */
	MAV_COMP_ID_USER57 MavComponent = 81

	/* Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network. */
	MAV_COMP_ID_USER58 MavComponent = 82

	/* Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network. */
	MAV_COMP_ID_USER59 MavComponent = 83

	/* Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network. */
	MAV_COMP_ID_USER60 MavComponent = 84

	/* Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network. */
	MAV_COMP_ID_USER61 MavComponent = 85

	/* Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network. */
	MAV_COMP_ID_USER62 MavComponent = 86

	/* Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network. */
	MAV_COMP_ID_USER63 MavComponent = 87

	/* Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network. */
	MAV_COMP_ID_USER64 MavComponent = 88

	/* Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network. */
	MAV_COMP_ID_USER65 MavComponent = 89

	/* Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network. */
	MAV_COMP_ID_USER66 MavComponent = 90

	/* Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network. */
	MAV_COMP_ID_USER67 MavComponent = 91

	/* Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network. */
	MAV_COMP_ID_USER68 MavComponent = 92

	/* Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network. */
	MAV_COMP_ID_USER69 MavComponent = 93

	/* Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network. */
	MAV_COMP_ID_USER70 MavComponent = 94

	/* Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network. */
	MAV_COMP_ID_USER71 MavComponent = 95

	/* Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network. */
	MAV_COMP_ID_USER72 MavComponent = 96

	/* Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network. */
	MAV_COMP_ID_USER73 MavComponent = 97

	/* Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network. */
	MAV_COMP_ID_USER74 MavComponent = 98

	/* Id for a component on privately managed MAVLink network. Can be used for any purpose but may not be published by components outside of the private network. */
	MAV_COMP_ID_USER75 MavComponent = 99

	/* Camera #1. */
	MAV_COMP_ID_CAMERA MavComponent = 100

	/* Camera #2. */
	MAV_COMP_ID_CAMERA2 MavComponent = 101

	/* Camera #3. */
	MAV_COMP_ID_CAMERA3 MavComponent = 102

	/* Camera #4. */
	MAV_COMP_ID_CAMERA4 MavComponent = 103

	/* Camera #5. */
	MAV_COMP_ID_CAMERA5 MavComponent = 104

	/* Camera #6. */
	MAV_COMP_ID_CAMERA6 MavComponent = 105

	/* Radio #1. */
	MAV_COMP_ID_RADIO MavComponent = 110

	/* Radio #2. */
	MAV_COMP_ID_RADIO2 MavComponent = 111

	/* Radio #3. */
	MAV_COMP_ID_RADIO3 MavComponent = 112

	/* Servo #1. */
	MAV_COMP_ID_SERVO1 MavComponent = 140

	/* Servo #2. */
	MAV_COMP_ID_SERVO2 MavComponent = 141

	/* Servo #3. */
	MAV_COMP_ID_SERVO3 MavComponent = 142

	/* Servo #4. */
	MAV_COMP_ID_SERVO4 MavComponent = 143

	/* Servo #5. */
	MAV_COMP_ID_SERVO5 MavComponent = 144

	/* Servo #6. */
	MAV_COMP_ID_SERVO6 MavComponent = 145

	/* Servo #7. */
	MAV_COMP_ID_SERVO7 MavComponent = 146

	/* Servo #8. */
	MAV_COMP_ID_SERVO8 MavComponent = 147

	/* Servo #9. */
	MAV_COMP_ID_SERVO9 MavComponent = 148

	/* Servo #10. */
	MAV_COMP_ID_SERVO10 MavComponent = 149

	/* Servo #11. */
	MAV_COMP_ID_SERVO11 MavComponent = 150

	/* Servo #12. */
	MAV_COMP_ID_SERVO12 MavComponent = 151

	/* Servo #13. */
	MAV_COMP_ID_SERVO13 MavComponent = 152

	/* Servo #14. */
	MAV_COMP_ID_SERVO14 MavComponent = 153

	/* Gimbal #1. */
	MAV_COMP_ID_GIMBAL MavComponent = 154

	/* Logging component. */
	MAV_COMP_ID_LOG MavComponent = 155

	/* Automatic Dependent Surveillance-Broadcast (ADS-B) component. */
	MAV_COMP_ID_ADSB MavComponent = 156

	/* On Screen Display (OSD) devices for video links. */
	MAV_COMP_ID_OSD MavComponent = 157

	/* Generic autopilot peripheral component ID. Meant for devices that do not implement the parameter microservice. */
	MAV_COMP_ID_PERIPHERAL MavComponent = 158

	/* Gimbal ID for QX1. */
	MAV_COMP_ID_QX1_GIMBAL MavComponent = 159

	/* FLARM collision alert component. */
	MAV_COMP_ID_FLARM MavComponent = 160

	/* Parachute component. */
	MAV_COMP_ID_PARACHUTE MavComponent = 161

	/* Winch component. */
	MAV_COMP_ID_WINCH MavComponent = 169

	/* Gimbal #2. */
	MAV_COMP_ID_GIMBAL2 MavComponent = 171

	/* Gimbal #3. */
	MAV_COMP_ID_GIMBAL3 MavComponent = 172

	/* Gimbal #4 */
	MAV_COMP_ID_GIMBAL4 MavComponent = 173

	/* Gimbal #5. */
	MAV_COMP_ID_GIMBAL5 MavComponent = 174

	/* Gimbal #6. */
	MAV_COMP_ID_GIMBAL6 MavComponent = 175

	/* Battery #1. */
	MAV_COMP_ID_BATTERY MavComponent = 180

	/* Battery #2. */
	MAV_COMP_ID_BATTERY2 MavComponent = 181

	/* CAN over MAVLink client. */
	MAV_COMP_ID_MAVCAN MavComponent = 189

	/* Component that can generate/supply a mission flight plan (e.g. GCS or developer API). */
	MAV_COMP_ID_MISSIONPLANNER MavComponent = 190

	/* Component that lives on the onboard computer (companion computer) and has some generic functionalities, such as settings system parameters and monitoring the status of some processes that don't directly speak mavlink and so on. */
	MAV_COMP_ID_ONBOARD_COMPUTER MavComponent = 191

	/* Component that lives on the onboard computer (companion computer) and has some generic functionalities, such as settings system parameters and monitoring the status of some processes that don't directly speak mavlink and so on. */
	MAV_COMP_ID_ONBOARD_COMPUTER2 MavComponent = 192

	/* Component that lives on the onboard computer (companion computer) and has some generic functionalities, such as settings system parameters and monitoring the status of some processes that don't directly speak mavlink and so on. */
	MAV_COMP_ID_ONBOARD_COMPUTER3 MavComponent = 193

	/* Component that lives on the onboard computer (companion computer) and has some generic functionalities, such as settings system parameters and monitoring the status of some processes that don't directly speak mavlink and so on. */
	MAV_COMP_ID_ONBOARD_COMPUTER4 MavComponent = 194

	/* Component that finds an optimal path between points based on a certain constraint (e.g. minimum snap, shortest path, cost, etc.). */
	MAV_COMP_ID_PATHPLANNER MavComponent = 195

	/* Component that plans a collision free path between two points. */
	MAV_COMP_ID_OBSTACLE_AVOIDANCE MavComponent = 196

	/* Component that provides position estimates using VIO techniques. */
	MAV_COMP_ID_VISUAL_INERTIAL_ODOMETRY MavComponent = 197

	/* Component that manages pairing of vehicle and GCS. */
	MAV_COMP_ID_PAIRING_MANAGER MavComponent = 198

	/* Inertial Measurement Unit (IMU) #1. */
	MAV_COMP_ID_IMU MavComponent = 200

	/* Inertial Measurement Unit (IMU) #2. */
	MAV_COMP_ID_IMU_2 MavComponent = 201

	/* Inertial Measurement Unit (IMU) #3. */
	MAV_COMP_ID_IMU_3 MavComponent = 202

	/* GPS #1. */
	MAV_COMP_ID_GPS MavComponent = 220

	/* GPS #2. */
	MAV_COMP_ID_GPS2 MavComponent = 221

	/* Open Drone ID transmitter/receiver (Bluetooth/WiFi/Internet). */
	MAV_COMP_ID_ODID_TXRX_1 MavComponent = 236

	/* Open Drone ID transmitter/receiver (Bluetooth/WiFi/Internet). */
	MAV_COMP_ID_ODID_TXRX_2 MavComponent = 237

	/* Open Drone ID transmitter/receiver (Bluetooth/WiFi/Internet). */
	MAV_COMP_ID_ODID_TXRX_3 MavComponent = 238

	/* Component to bridge MAVLink to UDP (i.e. from a UART). */
	MAV_COMP_ID_UDP_BRIDGE MavComponent = 240

	/* Component to bridge to UART (i.e. from UDP). */
	MAV_COMP_ID_UART_BRIDGE MavComponent = 241

	/* Component handling TUNNEL messages (e.g. vendor specific GUI of a component). */
	MAV_COMP_ID_TUNNEL_NODE MavComponent = 242

	/* Illuminator */
	MAV_COMP_ID_ILLUMINATOR MavComponent = 243

	/* Deprecated, don't use. Component for handling system messages (e.g. to ARM, takeoff, etc.). */
	MAV_COMP_ID_SYSTEM_CONTROL MavComponent = 250
)

/* Enum used to indicate true or false (also: success or failure, enabled or disabled, active or inactive). */
type MavBool uint32

const (
	/* False. */
	MAV_BOOL_FALSE MavBool = 0

	/* True. */
	MAV_BOOL_TRUE MavBool = 1
)

/* Bitmask of (optional) autopilot capabilities (64 bit). If a bit is set, the autopilot supports this capability. */
type MavProtocolCapability uint32

const (
	/* Autopilot supports the MISSION_ITEM float message type.           Note that MISSION_ITEM is deprecated, and autopilots should use MISSION_ITEM_INT instead.          */
	MAV_PROTOCOL_CAPABILITY_MISSION_FLOAT MavProtocolCapability = 1

	/* Autopilot supports the new param float message type. */
	MAV_PROTOCOL_CAPABILITY_PARAM_FLOAT MavProtocolCapability = 2

	/* Autopilot supports MISSION_ITEM_INT scaled integer message type.           Note that this flag must always be set if missions are supported, because missions must always use MISSION_ITEM_INT (rather than MISSION_ITEM, which is deprecated).          */
	MAV_PROTOCOL_CAPABILITY_MISSION_INT MavProtocolCapability = 4

	/* Autopilot supports COMMAND_INT scaled integer message type. */
	MAV_PROTOCOL_CAPABILITY_COMMAND_INT MavProtocolCapability = 8

	/* Parameter protocol uses byte-wise encoding of parameter values into param_value (float) fields: https://mavlink.io/en/services/parameter.html#parameter-encoding.           Note that either this flag or MAV_PROTOCOL_CAPABILITY_PARAM_ENCODE_C_CAST should be set if the parameter protocol is supported.          */
	MAV_PROTOCOL_CAPABILITY_PARAM_ENCODE_BYTEWISE MavProtocolCapability = 16

	/* Autopilot supports the File Transfer Protocol v1: https://mavlink.io/en/services/ftp.html. */
	MAV_PROTOCOL_CAPABILITY_FTP MavProtocolCapability = 32

	/* Autopilot supports commanding attitude offboard. */
	MAV_PROTOCOL_CAPABILITY_SET_ATTITUDE_TARGET MavProtocolCapability = 64

	/* Autopilot supports commanding position and velocity targets in local NED frame. */
	MAV_PROTOCOL_CAPABILITY_SET_POSITION_TARGET_LOCAL_NED MavProtocolCapability = 128

	/* Autopilot supports commanding position and velocity targets in global scaled integers. */
	MAV_PROTOCOL_CAPABILITY_SET_POSITION_TARGET_GLOBAL_INT MavProtocolCapability = 256

	/* Autopilot supports terrain protocol / data handling. */
	MAV_PROTOCOL_CAPABILITY_TERRAIN MavProtocolCapability = 512

	/* Reserved for future use. */
	MAV_PROTOCOL_CAPABILITY_RESERVED3 MavProtocolCapability = 1024

	/* Autopilot supports the MAV_CMD_DO_FLIGHTTERMINATION command (flight termination). */
	MAV_PROTOCOL_CAPABILITY_FLIGHT_TERMINATION MavProtocolCapability = 2048

	/* Autopilot supports onboard compass calibration. */
	MAV_PROTOCOL_CAPABILITY_COMPASS_CALIBRATION MavProtocolCapability = 4096

	/* Autopilot supports MAVLink version 2. */
	MAV_PROTOCOL_CAPABILITY_MAVLINK2 MavProtocolCapability = 8192

	/* Autopilot supports mission fence protocol. */
	MAV_PROTOCOL_CAPABILITY_MISSION_FENCE MavProtocolCapability = 16384

	/* Autopilot supports mission rally point protocol. */
	MAV_PROTOCOL_CAPABILITY_MISSION_RALLY MavProtocolCapability = 32768

	/* Reserved for future use. */
	MAV_PROTOCOL_CAPABILITY_RESERVED2 MavProtocolCapability = 65536

	/* Parameter protocol uses C-cast of parameter values to set the param_value (float) fields: https://mavlink.io/en/services/parameter.html#parameter-encoding.           Note that either this flag or MAV_PROTOCOL_CAPABILITY_PARAM_ENCODE_BYTEWISE should be set if the parameter protocol is supported.          */
	MAV_PROTOCOL_CAPABILITY_PARAM_ENCODE_C_CAST MavProtocolCapability = 131072

	/* This component implements/is a gimbal manager. This means the GIMBAL_MANAGER_INFORMATION, and other messages can be requested.          */
	MAV_PROTOCOL_CAPABILITY_COMPONENT_IMPLEMENTS_GIMBAL_MANAGER MavProtocolCapability = 262144

	/* Component supports locking control to a particular GCS independent of its system (via MAV_CMD_REQUEST_OPERATOR_CONTROL). */
	MAV_PROTOCOL_CAPABILITY_COMPONENT_ACCEPTS_GCS_CONTROL MavProtocolCapability = 524288

	/* Autopilot has a connected gripper. MAVLink Grippers would set MAV_TYPE_GRIPPER instead. */
	MAV_PROTOCOL_CAPABILITY_GRIPPER MavProtocolCapability = 1048576
)

/* These values define the type of firmware release.  These values indicate the first version or release of this type.  For example the first alpha release would be 64, the second would be 65. */
type FirmwareVersionType uint32

const (
	/* development release */
	FIRMWARE_VERSION_TYPE_DEV FirmwareVersionType = 0

	/* alpha release */
	FIRMWARE_VERSION_TYPE_ALPHA FirmwareVersionType = 64

	/* beta release */
	FIRMWARE_VERSION_TYPE_BETA FirmwareVersionType = 128

	/* release candidate */
	FIRMWARE_VERSION_TYPE_RC FirmwareVersionType = 192

	/* official stable release */
	FIRMWARE_VERSION_TYPE_OFFICIAL FirmwareVersionType = 255
)

// The Dialect factory function constructs the proper empty message given the message ID.
func Dialect(mid int) mavlink.Message {
	switch mid {
	case 0:
		return &Heartbeat{}
	case 33:
		return &GlobalPositionInt{}
	case 148:
		return &AutopilotVersion{}
	}
	return nil
}

/* The heartbeat message shows that a system or component is present and responding. The type and autopilot fields (along with the message component id), allow the receiving system to treat further messages from this system appropriately (e.g. by laying out the user interface based on the autopilot). This microservice is documented at https://mavlink.io/en/services/heartbeat.html */
type Heartbeat struct {
	/* A bitfield for use for autopilot-specific flags */
	CustomMode uint32

	/* Vehicle or component type. For a flight controller component the vehicle type (quadrotor, helicopter, etc.). For other components the component type (e.g. camera, gimbal, etc.). This should be used in preference to component id for identifying the component type. */
	Type MavType // byte

	/* Autopilot type / class. Use MAV_AUTOPILOT_INVALID for components that are not flight controllers. */
	Autopilot MavAutopilot // byte

	/* System mode bitmap. */
	BaseMode MavModeFlag // byte

	/* System status flag. */
	SystemStatus MavState // byte

	/* MAVLink version, not writable by user, gets added by protocol because of magic data type: uint8_t_mavlink_version */
	MavlinkVersion byte
}

func (m *Heartbeat) ID() int        { return 0 }
func (m *Heartbeat) CRCExtra() byte { return 50 }

func (m *Heartbeat) MarshalV1(buf []byte) []byte {
	buf = marshalUint32(buf, (m.CustomMode))
	buf = marshalByte(buf, byte(m.Type))
	buf = marshalByte(buf, byte(m.Autopilot))
	buf = marshalByte(buf, byte(m.BaseMode))
	buf = marshalByte(buf, byte(m.SystemStatus))
	buf = marshalByte(buf, (m.MavlinkVersion))

	return buf
}

func (m *Heartbeat) MarshalV2(buf []byte) []byte {
	buf = m.MarshalV1(buf)

	return buf
}

func (m *Heartbeat) UnmarshalV1(buf []byte) []byte {

	buf, m.CustomMode = unmarshalUint32(buf)

	{
		var v byte
		buf, v = unmarshalByte(buf)
		m.Type = MavType(v)
	}

	{
		var v byte
		buf, v = unmarshalByte(buf)
		m.Autopilot = MavAutopilot(v)
	}

	{
		var v byte
		buf, v = unmarshalByte(buf)
		m.BaseMode = MavModeFlag(v)
	}

	{
		var v byte
		buf, v = unmarshalByte(buf)
		m.SystemStatus = MavState(v)
	}

	buf, m.MavlinkVersion = unmarshalByte(buf)

	return buf
}

func (m *Heartbeat) UnmarshalV2(buf []byte) []byte {
	buf = m.UnmarshalV1(buf)

	return buf
}

/* The filtered global position (e.g. fused GPS and accelerometers). The position is in GPS-frame (right-handed, Z-up). It is designed as scaled integer message since the resolution of float is not sufficient. */
type GlobalPositionInt struct {
	/* Timestamp (time since system boot). */
	TimeBootMs uint32

	/* Latitude, expressed */
	Lat int32

	/* Longitude, expressed */
	Lon int32

	/* Altitude (MSL). Note that virtually all GPS modules provide both WGS84 and MSL. */
	Alt int32

	/* Altitude above home */
	RelativeAlt int32

	/* Ground X Speed (Latitude, positive north) */
	Vx int16

	/* Ground Y Speed (Longitude, positive east) */
	Vy int16

	/* Ground Z Speed (Altitude, positive down) */
	Vz int16

	/* Vehicle heading (yaw angle), 0.0..359.99 degrees. If unknown, set to: UINT16_MAX */
	Hdg uint16
}

func (m *GlobalPositionInt) ID() int        { return 33 }
func (m *GlobalPositionInt) CRCExtra() byte { return 104 }

func (m *GlobalPositionInt) MarshalV1(buf []byte) []byte {
	buf = marshalUint32(buf, (m.TimeBootMs))
	buf = marshalInt32(buf, (m.Lat))
	buf = marshalInt32(buf, (m.Lon))
	buf = marshalInt32(buf, (m.Alt))
	buf = marshalInt32(buf, (m.RelativeAlt))
	buf = marshalInt16(buf, (m.Vx))
	buf = marshalInt16(buf, (m.Vy))
	buf = marshalInt16(buf, (m.Vz))
	buf = marshalUint16(buf, (m.Hdg))

	return buf
}

func (m *GlobalPositionInt) MarshalV2(buf []byte) []byte {
	buf = m.MarshalV1(buf)

	return buf
}

func (m *GlobalPositionInt) UnmarshalV1(buf []byte) []byte {

	buf, m.TimeBootMs = unmarshalUint32(buf)

	buf, m.Lat = unmarshalInt32(buf)

	buf, m.Lon = unmarshalInt32(buf)

	buf, m.Alt = unmarshalInt32(buf)

	buf, m.RelativeAlt = unmarshalInt32(buf)

	buf, m.Vx = unmarshalInt16(buf)

	buf, m.Vy = unmarshalInt16(buf)

	buf, m.Vz = unmarshalInt16(buf)

	buf, m.Hdg = unmarshalUint16(buf)

	return buf
}

func (m *GlobalPositionInt) UnmarshalV2(buf []byte) []byte {
	buf = m.UnmarshalV1(buf)

	return buf
}

/* Version and capability of autopilot software. This should be emitted in response to a request with MAV_CMD_REQUEST_MESSAGE. */
type AutopilotVersion struct {
	/* Bitmap of capabilities */
	Capabilities MavProtocolCapability // uint64

	/* UID if provided by hardware (see uid2) */
	Uid uint64

	/* Firmware version number.         The field must be encoded as 4 bytes, where each byte (shown from MSB to LSB) is part of a semantic version: (major) (minor) (patch) (FIRMWARE_VERSION_TYPE).        */
	FlightSwVersion uint32

	/* Middleware version number */
	MiddlewareSwVersion uint32

	/* Operating system version number */
	OsSwVersion uint32

	/* HW / board version (last 8 bits should be silicon ID, if any). The first 16 bits of this field specify a board type from an enumeration stored at https://github.com/PX4/PX4-Bootloader/blob/master/board_types.txt and with extensive additions at https://github.com/ArduPilot/ardupilot/blob/master/Tools/AP_Bootloader/board_types.txt */
	BoardVersion uint32

	/* ID of the board vendor */
	VendorId uint16

	/* ID of the product */
	ProductId uint16

	/* Custom version field, commonly the first 8 bytes of the git hash. This is not an unique identifier, but should allow to identify the commit using the main version number even for very large code bases. */
	FlightCustomVersion [8]byte

	/* Custom version field, commonly the first 8 bytes of the git hash. This is not an unique identifier, but should allow to identify the commit using the main version number even for very large code bases. */
	MiddlewareCustomVersion [8]byte

	/* Custom version field, commonly the first 8 bytes of the git hash. This is not an unique identifier, but should allow to identify the commit using the main version number even for very large code bases. */
	OsCustomVersion [8]byte

	/* UID if provided by hardware (supersedes the uid field. If this is non-zero, use this field, otherwise use uid) */
	Uid2 [18]byte /*EXTENSION*/

}

func (m *AutopilotVersion) ID() int        { return 148 }
func (m *AutopilotVersion) CRCExtra() byte { return 178 }

func (m *AutopilotVersion) MarshalV1(buf []byte) []byte {
	buf = marshalUint64(buf, uint64(m.Capabilities))
	buf = marshalUint64(buf, (m.Uid))
	buf = marshalUint32(buf, (m.FlightSwVersion))
	buf = marshalUint32(buf, (m.MiddlewareSwVersion))
	buf = marshalUint32(buf, (m.OsSwVersion))
	buf = marshalUint32(buf, (m.BoardVersion))
	buf = marshalUint16(buf, (m.VendorId))
	buf = marshalUint16(buf, (m.ProductId))
	for _, v := range m.FlightCustomVersion {
		buf = marshalByte(buf, (v))
	}
	for _, v := range m.MiddlewareCustomVersion {
		buf = marshalByte(buf, (v))
	}
	for _, v := range m.OsCustomVersion {
		buf = marshalByte(buf, (v))
	}

	return buf
}

func (m *AutopilotVersion) MarshalV2(buf []byte) []byte {
	buf = m.MarshalV1(buf)
	for _, v := range m.Uid2 {
		buf = marshalByte(buf, (v))
	}

	return buf
}

func (m *AutopilotVersion) UnmarshalV1(buf []byte) []byte {

	{
		var v uint64
		buf, v = unmarshalUint64(buf)
		m.Capabilities = MavProtocolCapability(v)
	}

	buf, m.Uid = unmarshalUint64(buf)

	buf, m.FlightSwVersion = unmarshalUint32(buf)

	buf, m.MiddlewareSwVersion = unmarshalUint32(buf)

	buf, m.OsSwVersion = unmarshalUint32(buf)

	buf, m.BoardVersion = unmarshalUint32(buf)

	buf, m.VendorId = unmarshalUint16(buf)

	buf, m.ProductId = unmarshalUint16(buf)

	for i, _ := range m.FlightCustomVersion {
		buf, m.FlightCustomVersion[i] = unmarshalByte(buf)
	}

	for i, _ := range m.MiddlewareCustomVersion {
		buf, m.MiddlewareCustomVersion[i] = unmarshalByte(buf)
	}

	for i, _ := range m.OsCustomVersion {
		buf, m.OsCustomVersion[i] = unmarshalByte(buf)
	}

	return buf
}

func (m *AutopilotVersion) UnmarshalV2(buf []byte) []byte {
	buf = m.UnmarshalV1(buf)
	for i, _ := range m.Uid2 {
		buf, m.Uid2[i] = unmarshalByte(buf)
	}

	return buf
}

// These will be inlined.
func marshalByte(b []byte, v byte) []byte     { return append(b, v) }
func marshalInt8(b []byte, v int8) []byte     { return append(b, byte(v)) }
func marshalInt16(b []byte, v int16) []byte   { return append(b, byte(v), byte(v>>8)) }
func marshalUint16(b []byte, v uint16) []byte { return append(b, byte(v), byte(v>>8)) }
func marshalInt32(b []byte, v int32) []byte {
	return append(b, byte(v), byte(v>>8), byte(v>>16), byte(v>>24))
}
func marshalUint32(b []byte, v uint32) []byte {
	return append(b, byte(v), byte(v>>8), byte(v>>16), byte(v>>24))
}
func marshalInt64(b []byte, v int64) []byte {
	return append(b, byte(v), byte(v>>8), byte(v>>16), byte(v>>24), byte(v>>32), byte(v>>40), byte(v>>48), byte(v>>56))
}
func marshalUint64(b []byte, v uint64) []byte {
	return append(b, byte(v), byte(v>>8), byte(v>>16), byte(v>>24), byte(v>>32), byte(v>>40), byte(v>>48), byte(v>>56))
}
func marshalFloat32(b []byte, v float32) []byte { return marshalUint32(b, math.Float32bits(v)) }
func marshalFloat64(b []byte, v float64) []byte { return marshalUint64(b, math.Float64bits(v)) }

func unmarshalByte(b []byte) ([]byte, byte)     { return b[1:], b[0] }
func unmarshalInt8(b []byte) ([]byte, int8)     { return b[1:], int8(b[0]) }
func unmarshalInt16(b []byte) ([]byte, int16)   { return b[2:], int16(b[0]) | int16(b[1])<<8 }
func unmarshalUint16(b []byte) ([]byte, uint16) { return b[2:], uint16(b[0]) | uint16(b[1])<<8 }
func unmarshalInt32(b []byte) ([]byte, int32) {
	return b[4:], int32(b[0]) | int32(b[1])<<8 | int32(b[2])<<16 | int32(b[3])<<24
}
func unmarshalUint32(b []byte) ([]byte, uint32) {
	return b[4:], uint32(b[0]) | uint32(b[1])<<8 | uint32(b[2])<<16 | uint32(b[3])<<24
}
func unmarshalInt64(b []byte) ([]byte, int64) {
	return b[8:], int64(b[0]) | int64(b[1])<<8 | int64(b[2])<<16 | int64(b[3])<<24 | int64(b[4])<<32 | int64(b[5])<<40 | int64(b[6])<<48 | int64(b[7])<<56
}
func unmarshalUint64(b []byte) ([]byte, uint64) {
	return b[8:], uint64(b[0]) | uint64(b[1])<<8 | uint64(b[2])<<16 | uint64(b[3])<<24 | uint64(b[4])<<32 | uint64(b[5])<<40 | uint64(b[6])<<48 | uint64(b[7])<<56
}
func unmarshalFloat32(b []byte) ([]byte, float32) {
	b, v := unmarshalUint32(b)
	return b, math.Float32frombits(v)
}
func unmarshalFloat64(b []byte) ([]byte, float64) {
	b, v := unmarshalUint64(b)
	return b, math.Float64frombits(v)
}
